"$schema" = "https://starship.rs/config-schema.json"

[directory]
truncation_length = 10
truncate_to_repo = false

[time]
format = "[at](italic dimmed) [$time]($style) "
disabled = false

[battery]
disabled = true

[line_break]
disabled = true
